#include "cpu.h"

const struct cpu_instruction cpu_instructions[256] = {
    { "NOP", 1, 1 },                // 0x00
    { "LD BC, d16", 3, 3 },         
    { "LD (BC), A", 1, 2 },         
    { "INC BC", 1, 2 },             
    { "INC B", 1, 1 },             
    { "DEC B", 1, 1 },
    { "LD B, d8", 2, 2 },
    { "RLCA", 1, 1 },
    { "LD (a16), SP", 3, 5 },
    { "ADD HL, BC", 1, 2 },
    { "LD A, (BC)", 1, 2 },
    { "DEC BC", 1, 2 },
    { "INC C", 1, 1 },
    { "DEC C", 1, 1 },
    { "LD C, d8", 2, 2 },
    { "RRCA", 1, 1 },                         
    { "STOP", 2, 1 },               // 0x10
    { "LD DE, d16", 3, 3 },
    { "LD (DE), A", 1, 2 },
    { "INC DE", 1, 2 },
    { "INC D", 1, 1 },
    { "DEC D", 1, 1 },
    { "LD D, d8", 2, 2 },
    { "RLA", 1, 1 },
    { "JR s8", 2, 3 },
    { "ADD HL, DE", 1, 2 },
    { "LD A, (DE)", 1, 2 },
    { "DEC DE", 1, 2 },
    { "INC E", 1, 1 },
    { "DEC E", 1, 1 },
    { "LD E, d8", 2, 2 },
    { "RRA", 1, 1 },
    { "JR NZ, s8", 2, 32},          // 0x20
    { "LD HL, d16", 3, 3 },
    { "LD (HL+), A", 1, 2 },
    { "INC HL", 1, 2 },
    { "INC H", 1, 1 },
    { "DEC H", 1, 1 },
    { "LD H, d8", 2, 2 },
    { "DAA", 1, 1 },
    { "JR Z, s8", 2, 32},
    { "ADD HL, HL", 1, 2 },
    { "LD A, (HL+)", 1, 2 },
    { "DEC HL", 1, 2 },
    { "INC L", 1, 1 },
    { "DEC L", 1, 1 },
    { "LD L, d8", 2, 2 },
    { "CPL", 1, 1 },
    { "JR NC, s8", 2, 32},          // 0x30
    { "LD SP, d16", 3, 3 },
    { "LD (HL-), A", 1, 2 },
    { "INC SP", 1, 2 },
    { "INC (HL)", 1, 3 },
    { "DEC (HL)", 1, 3},
    { "LD (HL), d8", 2, 3 },
    { "SCF", 1, 1 },
    { "JR C, s8", 2, 32 },
    { "ADD HL, SP", 1, 2 },
    { "LD A, (HL-)", 1, 2 },
    { "DEC SP", 1, 2 },
    { "INC A", 1, 1 },
    { "DEC A", 1, 1 },
    { "LD A, d8", 2, 2 },
    { "CCF", 1, 1 },
    { "LD B, B", 1, 1 },            // 0x40
    { "LD B, C", 1, 1 },
    { "LD B, D", 1, 1 },
    { "LD B, E", 1, 1 },
    { "LD B, H", 1, 1},
    { "LD B, L", 1, 1},
    { "LD B, (HL)", 1, 2 },
    { "LD B, A", 1, 1 },
    { "LD C, B", 1, 1 },
    { "LD C, C", 1, 1 },
    { "LD C, D", 1, 1 },
    { "LD C, E", 1, 1 },
    { "LD C, H", 1, 1 },
    { "LD C, L", 1, 1 },
    { "LD C, (HL)", 1, 2 },
    { "LD C, A", 1, 1 },
    { "LD D, B", 1, 1 },             // 0x50
    { "LD D, C", 1, 1 },
    { "LD D, D", 1, 1 },
    { "LD D, E", 1, 1 },
    { "LD D, H", 1, 1 },
    { "LD D, L", 1, 1 },
    { "LD D, (HL)", 1, 2 },
    { "LD D, A", 1, 1 },
    { "LD E, B", 1, 1 },
    { "LD E, C", 1, 1 },
    { "LD E, D", 1, 1 },
    { "LD E, E", 1, 1 },
    { "LD E, H", 1, 1 },
    { "LD E, L", 1, 1 },
    { "LD E, (HL)", 1, 2 },
    { "LD E, A", 1, 1 },
    { "LD H, B", 1, 1 },              // 0x60
    { "LD H, C", 1, 1 },
    { "LD H, D", 1, 1 },
    { "LD H, E", 1, 1 },
    { "LD H, H", 1, 1 },
    { "LD H, L", 1, 1 },
    { "LD H, (HL)", 1, 2 },
    { "LD H, A", 1, 1 },
    { "LD L, B", 1, 1 },
    { "LD L, C", 1, 1 },
    { "LD L, D", 1, 1 },
    { "LD L, E", 1, 1 },
    { "LD L, H", 1, 1 },
    { "LD L, L", 1, 1 },
    { "LD L, (HL)", 1, 2 },
    { "LD L, A", 1, 1 },
    { "LD (HL), B", 1, 2 },            // 0x70
    { "LD (HL), C", 1, 2 },
    { "LD (HL), D", 1, 2 },
    { "LD (HL), E", 1, 2 },
    { "LD (HL), H", 1, 2 },
    { "LD (HL), L", 1, 2 },
    { "HALT", 1, 1 },
    { "LD (HL), A", 1, 2 },
    { "LD A, B", 1, 1 },
    { "LD A, C", 1, 1 },
    { "LD A, D", 1, 1 },
    { "LD A, E", 1, 1 },
    { "LD A, H", 1, 1 },
    { "LD A, L", 1, 1 },
    { "LD A, (HL)", 1, 2 },
    { "LD A, A", 1, 1 },
    { "ADD A, B", 1, 1 },               // 0x80
    { "ADD A, C", 1, 1 },
    { "ADD A, D", 1, 1 },
    { "ADD A, E", 1, 1 },
    { "ADD A, H", 1, 1 },
    { "ADD A, L", 1, 1 },
    { "ADD A, (HL)", 1, 2 },
    { "ADD A, A", 1, 1 },
    { "ADC A, B", 1, 1 },
    { "ADC A, C", 1, 1 },
    { "ADC A, D", 1, 1 },
    { "ADC A, E", 1, 1 },
    { "ADC A, H", 1, 1 },
    { "ADC A, L", 1, 1 },
    { "ADC A, (HL)", 1, 2 },
    { "ADC A, A", 1, 1 },
    { "SUB B", 1, 1 },                  // 0x90
    { "SUB C", 1, 1 },
    { "SUB D", 1, 1 },
    { "SUB E", 1, 1 },
    { "SUB H", 1, 1 },
    { "SUB L", 1, 1 },
    { "SUB (HL)", 1, 2 },
    { "SUB A", 1, 1 },
    { "SBC A, B", 1, 1 },
    { "SBC A, C", 1, 1 },
    { "SBC A, D", 1, 1 },
    { "SBC A, E", 1, 1 },
    { "SBC A, H", 1, 1 },
    { "SBC A, L", 1, 1 },
    { "SBC A, (HL)", 1, 2 },
    { "SBC A, A", 1, 1 },
    { "AND B", 1, 1},                   // 0xA0
    { "AND C", 1, 1},
    { "AND D", 1, 1},
    { "AND E", 1, 1},
    { "AND H", 1, 1},
    { "AND L", 1, 1},
    { "AND (HL)", 1, 2},
    { "AND A", 1, 1 },
    { "XOR B", 1, 1 },
    { "XOR C", 1, 1 },
    { "XOR D", 1, 1 },
    { "XOR E", 1, 1 },
    { "XOR H", 1, 1 },
    { "XOR L", 1, 1 },
    { "XOR (HL)", 1, 2 },
    { "XOR A", 1, 1 },
    { "OR B", 1, 1 },                    // 0xB0
    { "OR C", 1, 1 },
    { "OR D", 1, 1 },
    { "OR E", 1, 1 },
    { "OR H", 1, 1 },
    { "OR L", 1, 1 },
    { "OR (HL)", 1, 2 },
    { "OR A", 1, 1 },
    { "CP B", 1, 1 },
    { "CP C", 1, 1 },
    { "CP D", 1, 1 },
    { "CP E", 1, 1 },
    { "CP H", 1, 1 },
    { "CP L", 1, 1 },
    { "CP (HL)", 1, 2 },
    { "CP A", 1, 1 },
    { "RET NZ", 1, 52 },                 // 0xC0
    { "POP BC", 1, 3 },
    { "JP NZ, a16", 3, 43 },
    { "JP a16", 3, 4 },
    { "CALL NZ, a16", 3, 63 },
    { "PUSH BC", 1, 4 },
    { "ADD A, d8", 2, 2 },
    { "RST 0", 1, 4 },
    { "RET Z", 1, 52 },
    { "RET", 1, 4 },
    { "JP Z, a16", 3, 43 },
    { "NULL (0xCB)", 0, 0 },
    { "CALL Z, a16", 3, 63 },
    { "CALL a16", 3, 6 },
    { "ADC A, d8", 2, 2 },
    { "RST 1", 1, 4 },
    { "RET NC", 1, 52 },                 // 0xD0
    { "POP DE", 1, 3 },
    { "JP NC, a16", 3, 43 },
    { "NULL (0xD3)", 0, 0 },
    { "CALL NC, a16", 3, 63 },
    { "PUSH DE", 1, 4 },
    { "SUB d8", 2, 2 },
    { "RST 2", 1, 4 },
    { "RET C", 1, 52 },
    { "RETI", 1, 4 },
    { "JP C, a16", 3, 43 },
    { "NULL (0xDB)", 0, 0 },
    { "CALL C", 3, 63 },
    { "NULL (0xDD)", 0, 0 },
    { "SBC A, d8", 2, 2 },
    { "RST 3", 1, 4 },
    { "LD (a8), A", 2, 3 },             // 0xE0
    { "POP HL", 1, 3 },
    { "LD (C), A", 1, 2 },
    { "NULL (0xE3)", 0, 0 },
    { "NULL (0xE4)", 0, 0 },
    { "PUSH HL", 1, 4 },
    { "AND d8", 2, 2 },
    { "RST 4", 1, 4 },
    { "ADD SP, s8", 2, 4 },
    { "JP HL", 1, 1 },
    { "LD (a16), A", 3, 4 },
    { "NULL (0xEB)", 0, 0 },
    { "NULL (0xEC)", 0, 0 },
    { "NULL (0xED)", 0, 0 },
    { "XOR d8", 2, 2 },
    { "RST 5", 1, 4 },
    { "LD A, (a8)", 2, 3 },              // 0xF0
    { "POP AF", 1, 3 },
    { "LD A, (C)", 1, 2 },
    { "DI", 1, 1 },
    { "NULL (0xF4)", 0, 0 },
    { "PUSH AF", 1, 4 },
    { "OR d8", 2, 2 },
    { "RST 6", 1, 4 },
    { "LD HL, SP+s8", 2, 3 },
    { "LD SP, HL", 1, 2 },
    { "LD A, (a16)", 3, 4 },
    { "EI", 1, 1 },
    { "NULL (0xFC)", 0, 0 },
    { "NULL (0xFD)", 0, 0 },
    { "CP d8", 2, 2 },
    { "RST 7", 1, 4 }
};

const struct cpu_instruction cpu_prefix_cb_instructions[256] = {

};