#include <stdio.h>
#include <string.h>
#include "cpu.h"
#include "registers.h"
#include "mmu.h"

const struct cpu_instruction cpu_instructions[256] = {
    { "NOP", 1, 1 },                // 0x00
    { "LD BC, d16", 3, 3 },         
    { "LD (BC), A", 1, 2 },         
    { "INC BC", 1, 2 },             
    { "INC B", 1, 1 },             
    { "DEC B", 1, 1 },
    { "LD B, d8", 2, 2 },
    { "RLCA", 1, 1 },
    { "LD (a16), SP", 3, 5 },
    { "ADD HL, BC", 1, 2 },
    { "LD A, (BC)", 1, 2 },
    { "DEC BC", 1, 2 },
    { "INC C", 1, 1 },
    { "DEC C", 1, 1 },
    { "LD C, d8", 2, 2 },
    { "RRCA", 1, 1 },                         
    { "STOP", 2, 1 },               // 0x10
    { "LD DE, d16", 3, 3 },
    { "LD (DE), A", 1, 2 },
    { "INC DE", 1, 2 },
    { "INC D", 1, 1 },
    { "DEC D", 1, 1 },
    { "LD D, d8", 2, 2 },
    { "RLA", 1, 1 },
    { "JR s8", 2, 3 },
    { "ADD HL, DE", 1, 2 },
    { "LD A, (DE)", 1, 2 },
    { "DEC DE", 1, 2 },
    { "INC E", 1, 1 },
    { "DEC E", 1, 1 },
    { "LD E, d8", 2, 2 },
    { "RRA", 1, 1 },
    { "JR NZ, s8", 2, 32},          // 0x20
    { "LD HL, d16", 3, 3 },
    { "LD (HL+), A", 1, 2 },
    { "INC HL", 1, 2 },
    { "INC H", 1, 1 },
    { "DEC H", 1, 1 },
    { "LD H, d8", 2, 2 },
    { "DAA", 1, 1 },
    { "JR Z, s8", 2, 32},
    { "ADD HL, HL", 1, 2 },
    { "LD A, (HL+)", 1, 2 },
    { "DEC HL", 1, 2 },
    { "INC L", 1, 1 },
    { "DEC L", 1, 1 },
    { "LD L, d8", 2, 2 },
    { "CPL", 1, 1 },
    { "JR NC, s8", 2, 32},          // 0x30
    { "LD SP, d16", 3, 3 },
    { "LD (HL-), A", 1, 2 },
    { "INC SP", 1, 2 },
    { "INC (HL)", 1, 3 },
    { "DEC (HL)", 1, 3},
    { "LD (HL), d8", 2, 3 },
    { "SCF", 1, 1 },
    { "JR C, s8", 2, 32 },
    { "ADD HL, SP", 1, 2 },
    { "LD A, (HL-)", 1, 2 },
    { "DEC SP", 1, 2 },
    { "INC A", 1, 1 },
    { "DEC A", 1, 1 },
    { "LD A, d8", 2, 2 },
    { "CCF", 1, 1 },
    { "LD B, B", 1, 1 },            // 0x40
    { "LD B, C", 1, 1 },
    { "LD B, D", 1, 1 },
    { "LD B, E", 1, 1 },
    { "LD B, H", 1, 1},
    { "LD B, L", 1, 1},
    { "LD B, (HL)", 1, 2 },
    { "LD B, A", 1, 1 },
    { "LD C, B", 1, 1 },
    { "LD C, C", 1, 1 },
    { "LD C, D", 1, 1 },
    { "LD C, E", 1, 1 },
    { "LD C, H", 1, 1 },
    { "LD C, L", 1, 1 },
    { "LD C, (HL)", 1, 2 },
    { "LD C, A", 1, 1 },
    { "LD D, B", 1, 1 },             // 0x50
    { "LD D, C", 1, 1 },
    { "LD D, D", 1, 1 },
    { "LD D, E", 1, 1 },
    { "LD D, H", 1, 1 },
    { "LD D, L", 1, 1 },
    { "LD D, (HL)", 1, 2 },
    { "LD D, A", 1, 1 },
    { "LD E, B", 1, 1 },
    { "LD E, C", 1, 1 },
    { "LD E, D", 1, 1 },
    { "LD E, E", 1, 1 },
    { "LD E, H", 1, 1 },
    { "LD E, L", 1, 1 },
    { "LD E, (HL)", 1, 2 },
    { "LD E, A", 1, 1 },
    { "LD H, B", 1, 1 },              // 0x60
    { "LD H, C", 1, 1 },
    { "LD H, D", 1, 1 },
    { "LD H, E", 1, 1 },
    { "LD H, H", 1, 1 },
    { "LD H, L", 1, 1 },
    { "LD H, (HL)", 1, 2 },
    { "LD H, A", 1, 1 },
    { "LD L, B", 1, 1 },
    { "LD L, C", 1, 1 },
    { "LD L, D", 1, 1 },
    { "LD L, E", 1, 1 },
    { "LD L, H", 1, 1 },
    { "LD L, L", 1, 1 },
    { "LD L, (HL)", 1, 2 },
    { "LD L, A", 1, 1 },
    { "LD (HL), B", 1, 2 },            // 0x70
    { "LD (HL), C", 1, 2 },
    { "LD (HL), D", 1, 2 },
    { "LD (HL), E", 1, 2 },
    { "LD (HL), H", 1, 2 },
    { "LD (HL), L", 1, 2 },
    { "HALT", 1, 1 },
    { "LD (HL), A", 1, 2 },
    { "LD A, B", 1, 1 },
    { "LD A, C", 1, 1 },
    { "LD A, D", 1, 1 },
    { "LD A, E", 1, 1 },
    { "LD A, H", 1, 1 },
    { "LD A, L", 1, 1 },
    { "LD A, (HL)", 1, 2 },
    { "LD A, A", 1, 1 },
    { "ADD A, B", 1, 1 },               // 0x80
    { "ADD A, C", 1, 1 },
    { "ADD A, D", 1, 1 },
    { "ADD A, E", 1, 1 },
    { "ADD A, H", 1, 1 },
    { "ADD A, L", 1, 1 },
    { "ADD A, (HL)", 1, 2 },
    { "ADD A, A", 1, 1 },
    { "ADC A, B", 1, 1 },
    { "ADC A, C", 1, 1 },
    { "ADC A, D", 1, 1 },
    { "ADC A, E", 1, 1 },
    { "ADC A, H", 1, 1 },
    { "ADC A, L", 1, 1 },
    { "ADC A, (HL)", 1, 2 },
    { "ADC A, A", 1, 1 },
    { "SUB B", 1, 1 },                  // 0x90
    { "SUB C", 1, 1 },
    { "SUB D", 1, 1 },
    { "SUB E", 1, 1 },
    { "SUB H", 1, 1 },
    { "SUB L", 1, 1 },
    { "SUB (HL)", 1, 2 },
    { "SUB A", 1, 1 },
    { "SBC A, B", 1, 1 },
    { "SBC A, C", 1, 1 },
    { "SBC A, D", 1, 1 },
    { "SBC A, E", 1, 1 },
    { "SBC A, H", 1, 1 },
    { "SBC A, L", 1, 1 },
    { "SBC A, (HL)", 1, 2 },
    { "SBC A, A", 1, 1 },
    { "AND B", 1, 1},                   // 0xA0
    { "AND C", 1, 1},
    { "AND D", 1, 1},
    { "AND E", 1, 1},
    { "AND H", 1, 1},
    { "AND L", 1, 1},
    { "AND (HL)", 1, 2},
    { "AND A", 1, 1 },
    { "XOR B", 1, 1 },
    { "XOR C", 1, 1 },
    { "XOR D", 1, 1 },
    { "XOR E", 1, 1 },
    { "XOR H", 1, 1 },
    { "XOR L", 1, 1 },
    { "XOR (HL)", 1, 2 },
    { "XOR A", 1, 1 },
    { "OR B", 1, 1 },                    // 0xB0
    { "OR C", 1, 1 },
    { "OR D", 1, 1 },
    { "OR E", 1, 1 },
    { "OR H", 1, 1 },
    { "OR L", 1, 1 },
    { "OR (HL)", 1, 2 },
    { "OR A", 1, 1 },
    { "CP B", 1, 1 },
    { "CP C", 1, 1 },
    { "CP D", 1, 1 },
    { "CP E", 1, 1 },
    { "CP H", 1, 1 },
    { "CP L", 1, 1 },
    { "CP (HL)", 1, 2 },
    { "CP A", 1, 1 },
    { "RET NZ", 1, 52 },                 // 0xC0
    { "POP BC", 1, 3 },
    { "JP NZ, a16", 3, 43 },
    { "JP a16", 3, 4 },
    { "CALL NZ, a16", 3, 63 },
    { "PUSH BC", 1, 4 },
    { "ADD A, d8", 2, 2 },
    { "RST 0", 1, 4 },
    { "RET Z", 1, 52 },
    { "RET", 1, 4 },
    { "JP Z, a16", 3, 43 },
    { "NULL (0xCB)", 0, 0 },
    { "CALL Z, a16", 3, 63 },
    { "CALL a16", 3, 6 },
    { "ADC A, d8", 2, 2 },
    { "RST 1", 1, 4 },
    { "RET NC", 1, 52 },                 // 0xD0
    { "POP DE", 1, 3 },
    { "JP NC, a16", 3, 43 },
    { "NULL (0xD3)", 0, 0 },
    { "CALL NC, a16", 3, 63 },
    { "PUSH DE", 1, 4 },
    { "SUB d8", 2, 2 },
    { "RST 2", 1, 4 },
    { "RET C", 1, 52 },
    { "RETI", 1, 4 },
    { "JP C, a16", 3, 43 },
    { "NULL (0xDB)", 0, 0 },
    { "CALL C", 3, 63 },
    { "NULL (0xDD)", 0, 0 },
    { "SBC A, d8", 2, 2 },
    { "RST 3", 1, 4 },
    { "LD (a8), A", 2, 3 },             // 0xE0
    { "POP HL", 1, 3 },
    { "LD (C), A", 1, 2 },
    { "NULL (0xE3)", 0, 0 },
    { "NULL (0xE4)", 0, 0 },
    { "PUSH HL", 1, 4 },
    { "AND d8", 2, 2 },
    { "RST 4", 1, 4 },
    { "ADD SP, s8", 2, 4 },
    { "JP HL", 1, 1 },
    { "LD (a16), A", 3, 4 },
    { "NULL (0xEB)", 0, 0 },
    { "NULL (0xEC)", 0, 0 },
    { "NULL (0xED)", 0, 0 },
    { "XOR d8", 2, 2 },
    { "RST 5", 1, 4 },
    { "LD A, (a8)", 2, 3 },              // 0xF0
    { "POP AF", 1, 3 },
    { "LD A, (C)", 1, 2 },
    { "DI", 1, 1 },
    { "NULL (0xF4)", 0, 0 },
    { "PUSH AF", 1, 4 },
    { "OR d8", 2, 2 },
    { "RST 6", 1, 4 },
    { "LD HL, SP+s8", 2, 3 },
    { "LD SP, HL", 1, 2 },
    { "LD A, (a16)", 3, 4 },
    { "EI", 1, 1 },
    { "NULL (0xFC)", 0, 0 },
    { "NULL (0xFD)", 0, 0 },
    { "CP d8", 2, 2 },
    { "RST 7", 1, 4 }
};

const struct cpu_instruction cpu_prefix_cb_instructions[256] = {
    { "RLC B", 2, 2 },          // 0x00
    { "RLC C", 2, 2 },
    { "RLC D", 2, 2 },
    { "RLC E", 2, 2 },
    { "RLC H", 2, 2 },
    { "RLC L", 2, 2 },
    { "RLC (HL)", 2, 4 },
    { "RLC A", 2, 2 },
    { "RRC B", 2, 2 },
    { "RRC C", 2, 2 },
    { "RRC D", 2, 2 },
    { "RRC E", 2, 2 },
    { "RRC H", 2, 2 },
    { "RRC L", 2, 2 },
    { "RRC (HL)", 2, 4 },
    { "RRC A", 2, 2 },
    { "RL B", 2, 2 },           //0x10 
    { "RL C", 2, 2 },
    { "RL D", 2, 2 },
    { "RL E", 2, 2 },
    { "RL H", 2, 2 },
    { "RL L", 2, 2 },
    { "RL (HL)", 2, 4 },
    { "RL A", 2, 2 },
    { "RR B", 2, 2 },
    { "RR C", 2, 2 },
    { "RR D", 2, 2 },
    { "RR E", 2, 2 },
    { "RR H", 2, 2 },
    { "RR L", 2, 2 },
    { "RR (HL)", 2, 4 },
    { "RR A", 2, 2 },
    { "SLA B", 2, 2 },          // 0x20
    { "SLA C", 2, 2 },
    { "SLA D", 2, 2 },
    { "SLA E", 2, 2 },
    { "SLA H", 2, 2 },
    { "SLA L", 2, 2 },
    { "SLA (HL)", 2, 4 },
    { "SLA A", 2, 2 },
    { "SRA B", 2, 2 },
    { "SRA C", 2, 2 },
    { "SRA D", 2, 2 },
    { "SRA E", 2, 2 },
    { "SRA H", 2, 2 },
    { "SRA L", 2, 2 },
    { "SRA (HL)", 2, 4 },
    { "SRA A", 2, 2 },
    { "SWAP B", 2, 2},          // 0x30
    { "SWAP C", 2, 2},
    { "SWAP D", 2, 2},
    { "SWAP E", 2, 2},
    { "SWAP H", 2, 2},
    { "SWAP L", 2, 2},
    { "SWAP (HL)", 2, 4},
    { "SWAP A", 2, 2},
    { "SRL B", 2, 2 },
    { "SRL C", 2, 2 },
    { "SRL D", 2, 2 },
    { "SRL E", 2, 2 },
    { "SRL H", 2, 2 },
    { "SRL L", 2, 2 },
    { "SRL (HL)", 2, 4 },
    { "SRL A", 2, 2 },
    { "BIT 0, B", 2, 2 },           // 0x40
    { "BIT 0, C", 2, 2 },
    { "BIT 0, D", 2, 2 },
    { "BIT 0, E", 2, 2 },
    { "BIT 0, H", 2, 2 },
    { "BIT 0, L", 2, 2 },
    { "BIT 0, (HL)", 2, 3 },
    { "BIT 0, A", 2, 2 },
    { "BIT 1, B", 2, 2 },
    { "BIT 1, C", 2, 2 },
    { "BIT 1, D", 2, 2 },
    { "BIT 1, E", 2, 2 },
    { "BIT 1, H", 2, 2 },
    { "BIT 1, L", 2, 2 },
    { "BIT 1, (HL)", 2, 3 },
    { "BIT 1, A", 2, 2 },
    { "BIT 2, B", 2, 2 },           // 0x50
    { "BIT 2, D", 2, 2 },
    { "BIT 2, D", 2, 2 },
    { "BIT 2, E", 2, 2 },
    { "BIT 2, H", 2, 2 },
    { "BIT 2, L", 2, 2 },
    { "BIT 2, (HL)", 2, 3 },
    { "BIT 2, A", 2, 2 },
    { "BIT 3, B", 2, 2 },
    { "BIT 3, C", 2, 2 },
    { "BIT 3, D", 2, 2 },
    { "BIT 3, E", 2, 2 },
    { "BIT 3, H", 2, 2 },
    { "BIT 3, L", 2, 2 },
    { "BIT 3, (HL)", 2, 3 },
    { "BIT 3, A", 2, 2 },
    { "BIT 4, B", 2, 2 },            // 0x60
    { "BIT 4, C", 2, 2 },
    { "BIT 4, D", 2, 2 },
    { "BIT 4, E", 2, 2 },
    { "BIT 4, H", 2, 2 },
    { "BIT 4, L", 2, 2 },
    { "BIT 4, (HL)", 2, 3 },
    { "BIT 4, A", 2, 2 },
    { "BIT 5, B", 2, 2 },
    { "BIT 5, C", 2, 2 },
    { "BIT 5, D", 2, 2 },
    { "BIT 5, E", 2, 2 },
    { "BIT 5, H", 2, 2 },
    { "BIT 5, L", 2, 2 },
    { "BIT 5, (HL)", 2, 3 },
    { "BIT 5, A", 2, 2 },
    { "BIT 6, B", 2, 2 },           // 0x70
    { "BIT 6, C", 2, 2 },
    { "BIT 6, D", 2, 2 },
    { "BIT 6, E", 2, 2 },
    { "BIT 6, H", 2, 2 },
    { "BIT 6, L", 2, 2 },
    { "BIT 6, (HL)", 2, 3 },
    { "BIT 6, A", 2, 2 },
    { "BIT 7, B", 2, 2 },        
    { "BIT 7, C", 2, 2 },
    { "BIT 7, D", 2, 2 },
    { "BIT 7, E", 2, 2 },
    { "BIT 7, H", 2, 2 },
    { "BIT 7, L", 2, 2 },
    { "BIT 7, (HL)", 2, 3 },
    { "BIT 7, A", 2, 2 },
    { "RES 0, B", 2, 2 },           // 0x80
    { "RES 0, C", 2, 2 },
    { "RES 0, D", 2, 2 },
    { "RES 0, E", 2, 2 },
    { "RES 0, H", 2, 2 },
    { "RES 0, L", 2, 2 },
    { "RES 0, (HL)", 2, 4 },
    { "RES 0, A", 2, 2 },
    { "RES 1, B", 2, 2 },
    { "RES 1, C", 2, 2 },
    { "RES 1, D", 2, 2 },
    { "RES 1, E", 2, 2 },
    { "RES 1, H", 2, 2 },
    { "RES 1, L", 2, 2 },
    { "RES 1, (HL)", 2, 4 },
    { "RES 1, A", 2, 2 },
    { "RES 2, B", 2, 2 },           // 0x90
    { "RES 2, C", 2, 2 },
    { "RES 2, D", 2, 2 },
    { "RES 2, E", 2, 2 },
    { "RES 2, H", 2, 2 },
    { "RES 2, L", 2, 2 },
    { "RES 2, (HL)", 2, 4 },
    { "RES 2, A", 2, 2 },
    { "RES 3, B", 2, 2 },
    { "RES 3, C", 2, 2 },
    { "RES 3, D", 2, 2 },
    { "RES 3, E", 2, 2 },
    { "RES 3, H", 2, 2 },
    { "RES 3, L", 2, 2 },
    { "RES 3, (HL)", 2, 4 },
    { "RES 3, A", 2, 2 },
    { "RES 4, B", 2, 2 },           // 0xA0
    { "RES 4, C", 2, 2 },
    { "RES 4, D", 2, 2 },
    { "RES 4, E", 2, 2 },
    { "RES 4, H", 2, 2 },
    { "RES 4, L", 2, 2 },
    { "RES 4, (HL)", 2, 4 },
    { "RES 4, A", 2, 2 },
    { "RES 5, B", 2, 2 },
    { "RES 5, C", 2, 2 },
    { "RES 5, D", 2, 2 },
    { "RES 5, E", 2, 2 },
    { "RES 5, H", 2, 2 },
    { "RES 5, L", 2, 2 },
    { "RES 5, (HL)", 2, 4 },
    { "RES 5, A", 2, 2 },
    { "RES 6, B", 2, 2 },           // 0xB0
    { "RES 6, C", 2, 2 },
    { "RES 6, D", 2, 2 },
    { "RES 6, E", 2, 2 },
    { "RES 6, H", 2, 2 },
    { "RES 6, L", 2, 2 },
    { "RES 6, (HL)", 2, 4 },
    { "RES 6, A", 2, 2 },
    { "RES 7, B", 2, 2 },
    { "RES 7, C", 2, 2 },
    { "RES 7, D", 2, 2 },
    { "RES 7, E", 2, 2 },
    { "RES 7, H", 2, 2 },
    { "RES 7, L", 2, 2 },
    { "RES 7, (HL)", 2, 4 },
    { "RES 7, A", 2, 2 },
    { "SET 0, B", 2, 2 },           // 0xC0
    { "SET 0, C", 2, 2 },
    { "SET 0, D", 2, 2 },
    { "SET 0, E", 2, 2 },
    { "SET 0, H", 2, 2 },
    { "SET 0, L", 2, 2 },
    { "SET 0, (HL)", 2, 4 },
    { "SET 0, A", 2, 2 },
    { "SET 1, B", 2, 2 },         
    { "SET 1, C", 2, 2 },
    { "SET 1, D", 2, 2 },
    { "SET 1, E", 2, 2 },
    { "SET 1, H", 2, 2 },
    { "SET 1, L", 2, 2 },
    { "SET 1, (HL)", 2, 4 },
    { "SET 1, A", 2, 2 },
    { "SET 2, B", 2, 2 },           // 0xD0         
    { "SET 2, C", 2, 2 },
    { "SET 2, D", 2, 2 },
    { "SET 2, E", 2, 2 },
    { "SET 2, H", 2, 2 },
    { "SET 2, L", 2, 2 },
    { "SET 2, (HL)", 2, 4 },
    { "SET 2, A", 2, 2 },
    { "SET 3, B", 2, 2 },         
    { "SET 3, C", 2, 2 },
    { "SET 3, D", 2, 2 },
    { "SET 3, E", 2, 2 },
    { "SET 3, H", 2, 2 },
    { "SET 3, L", 2, 2 },
    { "SET 3, (HL)", 2, 4 },
    { "SET 3, A", 2, 2 },
    { "SET 4, B", 2, 2 },           // 0xE0         
    { "SET 4, C", 2, 2 },
    { "SET 4, D", 2, 2 },
    { "SET 4, E", 2, 2 },
    { "SET 4, H", 2, 2 },
    { "SET 4, L", 2, 2 },
    { "SET 4, (HL)", 2, 4 },
    { "SET 4, A", 2, 2 },
    { "SET 5, B", 2, 2 },         
    { "SET 5, C", 2, 2 },
    { "SET 5, D", 2, 2 },
    { "SET 5, E", 2, 2 },
    { "SET 5, H", 2, 2 },
    { "SET 5, L", 2, 2 },
    { "SET 5, (HL)", 2, 4 },
    { "SET 5, A", 2, 2 },
    { "SET 6, B", 2, 2 },           // 0xF0
    { "SET 6, C", 2, 2 },
    { "SET 6, D", 2, 2 },
    { "SET 6, E", 2, 2 },
    { "SET 6, H", 2, 2 },
    { "SET 6, L", 2, 2 },
    { "SET 6, (HL)", 2, 4 },
    { "SET 6, A", 2, 2 },
    { "SET 7, B", 2, 2 },         
    { "SET 7, C", 2, 2 },
    { "SET 7, D", 2, 2 },
    { "SET 7, E", 2, 2 },
    { "SET 7, H", 2, 2 },
    { "SET 7, L", 2, 2 },
    { "SET 7, (HL)", 2, 4 },
    { "SET 7, A", 2, 2 },
};

void cpu_reset() {
    memset(mmu.sram, 0, sizeof(mmu.sram));
    memset(mmu.vram, 0, sizeof(mmu.vram));
    memset(mmu.oam, 0, sizeof(mmu.oam));
    memset(mmu.wram, 0, sizeof(mmu.wram));
    memset(mmu.hram, 0, sizeof(mmu.hram));
    memcpy(mmu.io, mmu.bios, sizeof(mmu.io));

    cpu.stopped = false;
    cpu.ticks = 0;

    registers.a = 0x01;
    registers.f = 0xb0;
    registers.b = 0x00;
    registers.c = 0x13;
    registers.d = 0x00;
    registers.e = 0xd8;
    registers.h = 0x01;
    registers.l = 0x4d;
    registers.sp = 0xfffe;
    registers.pc = 0x100;
}

void cpu_emulate() {
    unsigned char instruction;
    unsigned short operand = 0;

    if (cpu.stopped) return;

    instruction = mmu_read_byte(registers.pc++);
    
    if(cpu_instructions[instruction].length == 1) cpu.operand = (unsigned short)mmu_read_byte(registers.pc);
	if(cpu_instructions[instruction].length == 2) cpu.operand = mmu_read_short(registers.pc);
	
    registers.pc += cpu_instructions[instruction].length;
    // TODO: add functions to all instruction tables
    // TODO: declare all functions in header for 
    switch(cpu_instructions[instruction].length) {
		case 0:
			((void (*)(void))cpu_instructions[instruction].function)();
			break;
		
		case 1:
			((void (*)(unsigned char))cpu_instructions[instruction].function)((unsigned char)cpu.operand);
			break;
		
		case 2:
			((void (*)(unsigned short))cpu_instructions[instruction].function)(cpu.operand);
			break;
	}
	
	cpu.ticks += cpu_instructions[instruction].cycles;
}

void cpu_unimplemented_instruction() {
    char mnemonic[20];
    registers.pc--;
    unsigned char instruction = mmu_read_byte(registers.pc);
    
    strcpy(mnemonic, cpu_instructions[instruction].mnemonic);
    printf("Unimplemented Instruction: %02x: %s\n", instruction, mnemonic);
}